name: vest-hive-test
region: nyc
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/ElCoditoBandito/vest-hive-test.git
    build_command: npm run build
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs